#!/usr/bin/python3
import random, sys

giftee = []
if len(sys.argv) > 1:
    from os import path

    fileName = sys.argv[1]
    if not path.exists(fileName):
        sys.exit('File does not exist')

    with open(fileName) as f:
      for line in f:
        line = line.strip()
        giftee.append(line)

else:
    print("Enter participants one at a time. Enter done when finished: ")
    name = ''
    while name != 'done' and name != 'Done':
        name = input('') 
        giftee.append(name)

    try:
        giftee.remove('done')
        giftee.remove('Done')
    except:
        pass

gifter = giftee.copy()
print(str(len(gifter)) + ' participants')
print('Pairings: ')


while len(gifter) != 0:
    name1Index = random.randint(0, len(gifter) - 1)
    name1 = gifter[name1Index]
    name2Index = random.randint(0, len(giftee) - 1)
    name2 = giftee[name2Index]

    # Ensure gifter does not receive themself
    while name2 == name1:
        name2Index = random.randint(0, len(giftee) - 1)
        name2 = giftee[name2Index]

    gifter.remove(gifter[name1Index])
    giftee.remove(name2)

    print(str(name1) + ', ' + str(name2))
